### PR TITLE
Replaced MixMaxRNG with a faster implementation

### PR DESCRIPTION
**Pull request by DiamonDinoia**
Dear all,

I have replaced the original MixMax implementation with a faster one. In my tests, this implementation is: 
| Compiler | Speed |
| -------- | ----- |
| clang 14 | +4%   |
| clang 13 | +6%   |
| gcc 12   | +17%  |
| gcc 11   | +16%  |  

Moreover, it reduces the state size by 1 element as there was duplication in the state of the original implementation.
This implementation has been tested against the original for 10^15 numbers (Left running for three months) and the results never diverged.

Thanks,
Marco

### CODE REVIEW

**Comment by drbenmorgan** [comment]
This looks very encouraging, thanks @DiamonDinoia! As the files changed are part of the CLHEP package which Geant4 provides a copy of here because it's always needed, it would be better to submit this to the primary CLHEP project at https://gitlab.cern.ch/CLHEP/CLHEP. That does require a CERN account though, so if you don't have one, we can assist in submitting the changes there, but @gcosmo should take a first pass review!

**Comment by DiamonDinoia** [comment]
Hi,
I could open a PR to CLHEP. Do I wait for your review first?

**Comment by DiamonDinoia** [comment]
I don't mind leaving credits correctly, I removed the implementation quote as it was untrue at this point, nothing against saying the original implementation was from Kostas. 
Moreover mixmax has been distributed under CLHEP/G4 license so anyone can change it according to that license.
There is also a version under boost license: https://github.com/boostorg/random/blob/develop/include/boost/random/mixmax.hpp

As long as the original source is from either or those I don't see any copyright issue.

**Comment by DiamonDinoia** [comment]
Sounds reasonable. I will do so.

**Comment by gcosmo** [comment]
The credits to the original implementation should be definitely restored and presented also in this new implementation, for matter of correctness, given that Kostas is also one of the authors of the engine itself.
BTW, I like your implementation. Much better polished than the original.
Indeed, it should be submitted directly to CLHEP as @drbenmorgan suggested. Then, if we can also obtain a review/approval from Kostas... the better!

**Comment by DiamonDinoia** [comment]
CLHEP pull request is here: https://gitlab.cern.ch/CLHEP/CLHEP/-/merge_requests

**Pull request closed without merging**
