### PR TITLE
Fix bug https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2455

### PR DESCRIPTION
**Pull request by zahiraam**
Signed-off-by: Zahira Ammarguellat <zahira.ammarguellat@intel.com>

### CODE REVIEW

**Comment by zahiraam** [comment]
Can someone look at this please? Thanks.

**Comment by zahiraam** [comment]
@sincerti  Review please? Thanks.

**Comment by tranngochoang** [comment]
Can you tell us which example you used for this ? dnadamage1 ? Thanks

**Comment by zahiraam** [comment]
> Can you tell us which example you used for this ? dnadamage1 ? Thanks

Thanks for your message.
I didn't use an example. This is a fail during the build of geant4 on windows.

**Comment by zahiraam** [comment]
@sincerti 
We also tried building the latest version geant4_11_0. It is building fine on Linux but failing on windows using the clang compiler.
These are the errors we are getting:
\geant4-master\source\global\management\include\G4Exp.hh(266): error C2146: syntax error: missing ')' before identifier 'iarray'
\geant4-master\source\global\management\include\G4Exp.hh(266): error C3646: 'iarray': unknown override specifier
\geant4-master\source\global\management\include\G4Exp.hh(267): error C2143: syntax error: missing ';' before '*'
\geant4-master\source\global\management\include\G4Exp.hh(267): error C2182: 'G4double': illegal use of type 'void'
\geant4-master\source\global\management\include\G4Exp.hh(267): error C2377: 'G4double': redefinition; typedef cannot be overloaded with any other symbol
\geant4-master\source\global\management\include\G4Exp.hh(267): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
\geant4-master\source\global\management\include\G4Exp.hh(267): error C2146: syntax error: missing ';' before identifier 'oarray'
\geant4-master\source\global\management\include\G4Exp.hh(267): error C2059: syntax error: ')'
\geant4-master\source\global\management\include\G4Exp.hh(268): error C2061: syntax error: identifier 'G4double'
\geant4-master\source\global\management\include\G4Exp.hh(270): error C2146: syntax error: missing ')' before identifier 'iarray'
\geant4-master\source\global\management\include\G4Exp.hh(270): error C3646: 'iarray': unknown override specifier
\geant4-master\source\global\management\include\G4Exp.hh(271): error C2143: syntax error: missing ';' before '*'
\geant4-master\source\global\management\include\G4Exp.hh(271): error C2182: 'G4float': illegal use of type 'void'
\geant4-master\source\global\management\include\G4Exp.hh(271): error C2377: 'G4float': redefinition; typedef cannot be overloaded with any other symbol
\geant4-master\source\global\management\include\G4Exp.hh(271): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
\geant4-master\source\global\management\include\G4Exp.hh(271): error C2086: 'int *__restrict__': redefinition
\geant4-master\source\global\management\include\G4Exp.hh(271): error C2146: syntax error: missing ';' before identifier 'oarray'
\geant4-master\source\global\management\include\G4Exp.hh(271): error C2059: syntax error: ')'
\geant4-master\source\global\management\include\G4Exp.hh(272): error C2061: syntax error: identifier 'G4float'
\geant4-master\source\externals\clhep\include\CLHEP/Utility/thread_local.h(10): fatal error C1017: invalid integer constant expression
\geant4-master\source\externals\clhep\include\CLHEP/Utility/thread_local.h(10): fatal error C1017: invalid integer constant expression
make[2]: *** [source/CMakeFiles/G4global.dir/global/HEPRandom/src/G4Poisson.cc.obj] Error 2
make[2]: *** [source/CMakeFiles/G4global.dir/global/HEPRandom/src/G4UniformRandPool.cc.obj] Error 2
make[1]: *** [source/CMakeFiles/G4global.dir/all] Error 2

Meanwhile is the change I am proposing in this patch acceptable to you?

**Comment by gcosmo** [comment]
Hi Zahira, the clang compiler on Windows is a configuration we do NOT support and never tested. The errors shown likely indicate a misconfiguration and not a problem in the code, but we are not in the position to confirm this. Sorry.

**Comment by tranngochoang** [comment]
@zahiraam We did some tests of the clang on Windows. We realize that there are a lot problems with clang. I wonder that you can go to the issue cause I cannot compile G4 with clang.

**Comment by zahiraam** [comment]
> @zahiraam We did some tests of the clang on Windows. We realize that there are a lot problems with clang. I wonder that you can go to the issue cause I cannot compile G4 with clang. I cannot test the commit for this moment.

Thanks for your reply. Let me make things a little clearer. The patch in this PR was to fix an issue that we got when building an older version of geant4 (geant4_10). 
When I asked QA to use the newer version, they listed the errors above. The errors are obviously not clang errors but MSVC ones. @gcosmo is suggesting that it might be a configuration issue. It might be! I will confirm with QA and let you know. Please note that on Linux we didn't have any issues building both versions of geant4.

**Comment by gcosmo** [comment]
The clang compiler is tested and supported for Geant4 only on macOS and Linux platforms. You should use MS/Visual-Studio on Windows. See the list of supported compilers reported for each version of Geant4 in the respective release notes.

**Pull request closed without merging**
