### PR TITLE
FindCLHEP is obsolete; CLHEP follows cmake standard

### PR DESCRIPTION
**Pull request by whit2333**
For use of a system CLHEP this file breaks the cmake build.

### CODE REVIEW

**Comment by drbenmorgan** [comment]
Thanks for the PR - as this repo is only for mirroring releases, I've added an entry in our Bugzilla mapping to it.

https://bugzilla-geant4.kek.jp/show_bug.cgi?id=1934

Further updates will be made on that ticket, and I'll close the PR (it cannot be merged here) once the Bugzilla is marked RESOLVED CLOSED.

**Comment by whit2333** [comment]
Thanks!

On Mon, Jan 16, 2017 at 05:56:55AM -0800, Ben Morgan wrote:
>Thanks for the PR - as this repo is only for mirroring releases, I've added an entry in our Bugzilla mapping to it.
>
>https://bugzilla-geant4.kek.jp/show_bug.cgi?id=1934
>
>Further updates will be made on that ticket, and I'll close the PR (it cannot be merged here) once the Bugzilla is marked RESOLVED CLOSED.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Geant4/geant4/pull/1#issuecomment-272867915

-- 
Whitney R. Armstrong

**Comment by drbenmorgan** [comment]
This is now fixed in the main SVN repo in tag cmake-V10-03-11. Note that additional changes other than simple removal of FindCLHEP were required. The fix may just make the upcoming patch to 10.3, but I can't guarantee this.

**Comment by whit2333** [comment]
FYI it is still a problem. FindCLHEP.cmake **should not** be installed. A stand alone CLHEP install  does not need a find moudle. It works just find in "config" mode.

**Pull request closed without merging**
