### PR TITLE
ScaledSolid and MultiUnion added in ascii geometry

### PR DESCRIPTION
**Pull request by p1heidary**
I have implemented G4tgrScaledSolid and G4tgrMultiUnion in text geometry. Added classes was inspired by G4tgrSolidBoolean. These classes can be used for creating cladding around a complex shape reflector(for instance).

### CODE REVIEW

**Comment by p1heidary** [comment]
Thanx for reviewing my PR. All comments resolved, please take another look.

**Comment by arceciemat** [comment]
It is OK to me. Although I would call the class G4tgrSolidMultiUnion, it is clearer and we do not have to care for a name a bit longer

**Comment by arceciemat** [comment]
Hi Pooria, I accept your code and will pass it to the official release. I hope you do not mind for the change of name to  G4tgrSolidMultiUnion

**Review by arceciemat — APPROVED** [review]

**Comment by p1heidary** [comment]
Thank you Pedro.
The changes are useful for sure. If I can do more help, don't hesitate to ask me.

**Comment by p1heidary** [comment]
Thanx for processing my PR.

**Pull request closed without merging**
