### PR TITLE
Generic cutaway added

### PR DESCRIPTION
**Pull request by p1heidary**
This PR adds generic cutaway to G4VSceneHandler which can be used by visualization drivers that does not include it (e.g. Qt3D, VTK, ToolsSG).

### CODE REVIEW

**Comment by johna1941** [comment]
Quick comment...

I believe there is cutaway (and section) code in G4PhysicalVolumeModel using Boolean intersection/subtraction. Have you looked at that?

**Comment by johna1941** [comment]
Ah! Great! On deeper inspection of your PR it follows exactly the design of G4vis/modelling and implements a function that has somehow been forgotten. Well, not actually forgotten, because, as it says, there is an alternative way of getting a cutaway using /vis/scene/add/volume. Still, it should have been implemented.

I will test your PR.

**Comment by johna1941** [comment]
Hi Pooria

Ah, yes. I had forgotten our previous correspondence. You are right about "the alternate way" - it is limited to a cutaway box, i.e., perpendicular cut planes. So your way is the general way to do it.

Give me a little more time to understand exactly what you have done and to test it. It would be good to have some inline comments that explain the strategy - and include also, perhaps, your name and a date?

John

**Comment by p1heidary** [comment]
Thank you John

I will consider adding inline comments in future PRs. the strategy is the same as the section_solid (a couple of lines above).
As ny previous contributions, I think name and date is added in History file.

**Comment by johna1941** [comment]
Hi Pooria

I'm just getting down to look at your PR. I am beginning to remember why we did not implement this. :-(

The problem is that if a volume is entirely outside or entirely inside the cutaway solid, it is left unchanged - or rather the polyhedron which represents it is unchanged. As things stand, the code in G4PhysicalVolumeModel simply recognises unchanged polyhedra and does not draw them. You can see this effect if you make a cutaway plane that is a long way displaced from your volumes of interest: if it is displaced in one direction, your volumes will disappear, if in the opposite direction, they still disappear. In one of the cases, they should *not* disappear.

What we need to do is:
- make the solid to polyhedron conversion smarter, so that in the case of a subtraction, if the subtractee is entirely inside the subtractor, a null polyhedron is returned and, conversely, if it is entirely outside, the original is returned; or
- make G4PhysicalVolumeModel smarter so that it can tell the difference.

I can ask for the former (but it's not my area of responsibility), or I can try the latter. Meanwhile I'll keep your code on a topic branch and work on it.

There is a minor issue of sign convention: it seems opposite to OpenGL. It is fixed if
```
      const G4Normal3D newNormal(a,b,c);
```
is replaced by
```
      const G4Normal3D newNormal(-a,-b,-c);
```

Anyway, I'm happy to progress this for the next release.

John

**Comment by johna1941** [comment]
Hi Pooria

After fighting some bugs in other parts of Geant4 I finally succeeded in merging generic cutaways into the master to my satisfaction for the next release (December). Your code is mostly as you proposed - very nice design. Thankyou for your initiative and prompting us to revisit this issue and make progress.

John

**Comment by p1heidary** [comment]
Hi John
Because of your heavy (inline) comments, visualisation codes are fully readable and easy to extend.
Thanx for your time and attention.

**Comment by johna1941** [comment]
Generic cutaway is now implemented in Geant4 11.1. Thank you, Pooria, for your very nice work.

John

**Pull request closed without merging**
