### PR TITLE
Assorted code improvements

### PR DESCRIPTION
**Pull request by loximann**
- Align the behavior of G4HadronicException with std::exception: what() returns
  the exception explanation.
- Move the member definition to a source file.
- Added some consts.
- Replaced some tabs in sources.cmake with spaces.

### CODE REVIEW

**Comment by loximann** [comment]
The main reason for this change was to be able to extract information when a G4HadronicException was thrown, without needing to include Geant4.

There are no changes to the public API (well, G4HadronicException::Report() is now a const member function, that that should not affect external projects?).

**Comment by loximann** [comment]
I noticed that it is possible to instantiate G4HadronicProcess to have whichever G4ProcessType. I removed the constructor, which is apparently not used anywhere.

**Comment by ihrivnac** [comment]
Hello,
Thank you for the proposed improvements. They are now under evaluation and testing. We will update this thread when testing is finished.
Best regards,

**Comment by loximann** [comment]
Lovely, thanks :-)

**Comment by ihrivnac** [comment]
The commits with description 
- Improvements to G4HadronicException
- All boolean operators now return G4bool.
are now included in Geant4 development version.

The other two proposals:
- Remove unused and potentially dangerous G4HadronicProcess constructor.
- Fixed the value of the G4ProcessType argument in many process constru...
will need to be planned, as they imply changes in the interfaces.

Next time, please, prefer to open standalone PRs based on a fix topic, 
rather than grouping things of different type together. 

Best regards,

**Comment by loximann** [comment]
Thanks for looking into it. I agree about separating the changes into different PRs, my apologies.

**Comment by gcosmo** [comment]
Closing PR.

**Pull request closed without merging**
